### PR TITLE
[PictureInPicture] Update the PiP samples

### PR DESCRIPTION
**Pull request by yaraki**
Update dependencies.

Replace deprecated APIs.
- Replace ActivityTestRule with ActivityScenarioRule
- Replace systemUiVisibility with WindowInsetsControllerCompat

Use the new Kotlin code style. Remove m- prefix.

Change-Id: If83997ed4ee689b8b481af44fa4cf833fccfb4f7

### CODE REVIEW

**Comment by yaraki** [comment]
This doesn't contain any new preview APIs yet. Just general clean up.

**Review by chrisbanes — APPROVED** [review]
LGTM, is it worth converting this to Kotlin? (doesn't need to be done in this PR)

**Comment by yaraki** [comment]
> LGTM, is it worth converting this to Kotlin? (doesn't need to be done in this PR)

There are PictureInPicture and PictureInPictureKotlin, and this PR updates both.

**Comment by chrisbanes** [comment]
> There are PictureInPicture and PictureInPictureKotlin, and this PR updates both.

Ah, do we need both? I wondering whether we  `rm -r PictureInPicture && mv PictureInPictureKotlin PictureInPicture`

**Comment by codingjeremy** [comment]
That's an interesting idea. We keep them separate right now, so devs can see which samples have Kotlin versions in Studio imports and on the DAC samples page.

I will bring up with our internal group to discuss.

**Review by codingjeremy — APPROVED** [review]

**Pull request merged**
